---

- name: Deploy web application
  hosts: all
  become: yes
  tasks:
    - name: update the packages
      command: sudo apt-get update
    - name: Install dependencies
      apt:
        name: '{{ item }}'
        state: present
      with_items:
        - python3
        - python3-setuptools
        - python3-dev
        - build-essential
        - python3-pip
        - python3-mysqldb
    - name: Install database
      apt:
        name: '{{ item }}'
        state: present
      with_items:
        - mysql-server
        - mysql-client
    - name: Start mysql service
      service:
        name: mysql
        state: started
        enabled: yes
    - name: create a database
      mysql_db:
        name: employee_db
        state: present
    - name: create database user
      mysql_user:
        name: db_user
        password: Passw0rd
        priv: "*.*:ALL"
        host: "%"
        state: present
    - name: install flask dependencies
      pip:
        name: '{{ item }}'
        state: present
      with_items:
        - flask
        - flask-mysql
    - name: Copy application code
      copy:
        src: app.py
        dest: /opt/app.py
    - name: Start web-application
      shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &



