---
# tasks file for mysql_db
    - name: Install database
      apt:
        name: '{{ item }}'
        state: present
      with_items:
        - mysql-server
        - mysql-client
    - name: Start mysql service
      service:
        name: mysql
        state: started
        enabled: yes
    - name: create a database
      mysql_db:
        name: employee_db
        state: present
    - name: create database user
      mysql_user:
        name: '{{ db_user }}'
        password: '{{ db_password }}'
        priv: "*.*:ALL"
        host: "%"
        state: present
